name: Check for broken links

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**/*.md'

jobs:
  check-links:
    name: Check for broken links
    runs-on: ubuntu-latest
    
    permissions:
      issues: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install markdown-link-check
        run: npm install markdown-link-check
      
      - name: Check links in README.md
        run: npx markdown-link-check --config .github/workflows/link-check-config.json README.md
      
      - name: Check links in docs directory
        run: find docs -name "*.md" -exec npx markdown-link-check --config .github/workflows/link-check-config.json {} \;
      
      - name: Check links in other markdown files
        run: |
          find . -name "*.md" -not -path "./node_modules/*" -not -path "./docs/*" -not -path "./README.md" -exec npx markdown-link-check --config .github/workflows/link-check-config.json {} \;
      
      - name: Create issue if links are broken
        if: ${{ failure() }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Broken links detected',
              body: 'The link checker has detected broken links in the repository. Please check the workflow logs for details.',
              labels: ['bug', 'documentation']
            })